USE FS_CAD

IF NOT EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'FSENTUSU')
CREATE TABLE [FSENTUSU](
	USUNID_ENT [INT]           NOT NULL IDENTITY (1, 1),
	USUCAPELID [VARCHAR](15)   NOT NULL, -- NOME DE USU�RIO 
	USUC_EMAIL [VARCHAR](320)   NOT NULL, -- EMAIL DE USU�RIO VARCHAR(320)
	USUCUSUSEN [VARCHAR](20)   NOT NULL, -- SENHA DE USU�RIO
	USUCUSUCAD [VARCHAR](15)       NULL, -- USU�RIO DE CADASTRO
	USUDDATCAD [DATETIME]          NULL, -- DATA DE CADASTRO
	USUCUSUALT [VARCHAR](15)       NULL, -- USU�RIO DE ALTERA��O
	USUDDATALT [DATETIME]          NULL  -- DATA DE ALTERA��O
	) ON [PRIMARY]

		
IF NOT EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'FSAIRTAG')
CREATE TABLE [FSAIRTAG](
	AIRNID_AIR [INT]           NOT NULL IDENTITY (1, 1),
	AIRCDESCRI [VARCHAR](25)   NOT NULL, -- DESCRI��O DA AIRTAG
	AIRCIP_ADR [CHAR](15)      NOT NULL, -- ENDERE�O DE IP
	AIRCMACADR [CHAR](20)      NOT NULL, -- ENDERE�O DE MAC
	AIRCUSUCAD [VARCHAR](15)       NULL, -- USU�RIO DE CADASTRO
	AIRDDATCAD [DATETIME]          NULL, -- DATA DE CADASTRO
	AIRCUSUALT [VARCHAR](15)       NULL, -- USU�RIO DE ALTERA��O
	AIRDDATALT [DATETIME]          NULL  -- DATA DE ALTERA��O
	) ON [PRIMARY]

IF NOT EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'FSAIRTAG_USU')
CREATE TABLE [FSAIRTAG_USU](
	ATSNID_ATS [INT]           NOT NULL IDENTITY (1, 1),
	ATSNID_USU [INT]		   NOT NULL, -- ID DO USUPARIO	
	ATSNID_AIR [INT]           NOT NULL, -- ID DA AIRTAG
	ATSCUSUCAD [VARCHAR](15)       NULL, -- USU�RIO DE CADASTRO
	ATSDDATCAD [DATETIME]          NULL, -- DATA DE CADASTRO
	ATSCUSUALT [VARCHAR](15)       NULL, -- USU�RIO DE ALTERA��O
	ATSDDATALT [DATETIME]          NULL  -- DATA DE ALTERA��O
	) ON [PRIMARY]

--PRIMARY KEYS	
IF OBJECT_ID('FSENTUSU_PK','PK') IS NULL
ALTER TABLE FSENTUSU 	 ADD CONSTRAINT FSENTUSU_PK 	PRIMARY KEY CLUSTERED (USUNID_ENT) 	WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
		
IF OBJECT_ID('FSAIRTAG_PK','PK') IS NULL
ALTER TABLE FSAIRTAG 	 ADD CONSTRAINT FSAIRTAG_PK 	PRIMARY KEY CLUSTERED (AIRNID_AIR) 	WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

IF OBJECT_ID('FSAIRTAG_USU_PK','PK') IS NULL
ALTER TABLE FSAIRTAG_USU ADD CONSTRAINT FSAIRTAG_USU_PK PRIMARY KEY CLUSTERED (ATSNID_ATS) 	WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

--FOREIGN KEY
IF OBJECT_ID('ATSNID_AIR_RL_TAG','F') IS NULL
ALTER TABLE FSAIRTAG_USU WITH CHECK ADD  CONSTRAINT ATSNID_AIR_RL_TAG FOREIGN KEY(ATSNID_AIR) REFERENCES FSAIRTAG (AIRNID_AIR) 
ALTER TABLE FSAIRTAG_USU      CHECK      CONSTRAINT ATSNID_AIR_RL_TAG

IF OBJECT_ID('ATSNID_USU_RL_USU','F') IS NULL
ALTER TABLE FSAIRTAG_USU WITH CHECK ADD  CONSTRAINT ATSNID_USU_RL_USU FOREIGN KEY(ATSNID_USU) REFERENCES FSENTUSU (USUNID_ENT) 
ALTER TABLE FSAIRTAG_USU      CHECK      CONSTRAINT ATSNID_USU_RL_USU


--NONCLUSTERED INDEXES
IF NOT EXISTS (SELECT NAME FROM sys.indexes WHERE name = 'FSAIRTAG_USU_IX_USU_AIR' AND object_id = OBJECT_ID('FSAIRTAG_USU'))
CREATE UNIQUE   NONCLUSTERED INDEX FSAIRTAG_USU_IX_USU_AIR ON FSAIRTAG_USU (ATSNID_USU, ATSNID_AIR)            
WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

IF NOT EXISTS (SELECT NAME FROM sys.indexes WHERE name = 'FSAIRTAG_IX_AIRCMACADR' AND object_id = OBJECT_ID('FSAIRTAG'))
CREATE UNIQUE  NONCLUSTERED INDEX FSAIRTAG_IX_AIRCMACADR ON FSAIRTAG (AIRCMACADR)            
WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'FSLOGLOG')
CREATE TABLE [FSLOGLOG](
	[LOGCTABELA] [varchar](50) NOT NULL,
	[LOGCID_REC] [varchar](50) NOT NULL,
	[LOGCTIPALT] [char](1) NOT NULL,
	[LOGMXMLREC] [xml] NOT NULL,
	[LOGCUSUALT] [varchar](50) NOT NULL,
	[LOGDDATALT] [datetime] NOT NULL,
	[LOGNID_LOG] [int] IDENTITY(1,1) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

-- CRIAR USU�RIO FINDER
IF EXISTS (SELECT * FROM sys.syslogins where name='FINDER')
		ALTER LOGIN [FINDER] WITH PASSWORD = '123', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF, DEFAULT_LANGUAGE = Brazilian
ELSE
	CREATE LOGIN [FINDER] WITH PASSWORD = '123', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF, DEFAULT_LANGUAGE = Brazilian
	
EXEC sys.sp_addsrvrolemember @loginame = 'FINDER', @rolename = N'sysadmin'

EXEC sp_msforeachdb @command1 = 'USE ? 
	IF NOT EXISTS (SELECT * FROM SYS.DATABASE_PRINCIPALS WHERE TYPE=''S'' AND NAME=''FINDER'')
		BEGIN
			CREATE USER [FINDER] FROM LOGIN [FINDER]

			EXEC SP_ADDROLEMEMBER ''DB_DATAREADER'', ''FINDER''

			EXEC SP_ADDROLEMEMBER ''DB_DATAWRITER'', ''FINDER''

		END '

IF NOT EXISTS (SELECT USUNID_ENT FROM FS_CAD..FSENTUSU WHERE USUCAPELID ='FINDER' AND USUCUSUSEN = '123')
INSERT INTO FS_CAD..FSENTUSU (USUCAPELID, USUCUSUSEN) VALUES ('FINDER','123')		
