IF OBJECT_ID('FSAIRTAG_USU_TR_INC_ALT_DEL','TR') IS NULL
EXEC('	
	CREATE TRIGGER FSAIRTAG_USU_TR_INC_ALT_DEL
	   ON FSAIRTAG_USU
	   AFTER INSERT,UPDATE,DELETE
	AS

	DECLARE @LOGCTABELA VARCHAR(50)
	DECLARE @LOGCID_REC VARCHAR(50)
	DECLARE @LOGMXMLREC XML
	DECLARE @LOGCTIPALT CHAR(01)
	DECLARE @ATSNID_ATS INT

	SET @LOGCTABELA = ''FSAIRTAG_USU''
	SET @LOGCTIPALT = ''I''

	DECLARE @COUNT AS INT
	SELECT  @COUNT = COUNT(*) FROM DELETED

	IF @COUNT > 0
		BEGIN
			SET @LOGCTIPALT = ''E''
			SELECT @COUNT = COUNT(*) FROM INSERTED
			IF @COUNT > 0
				SET @LOGCTIPALT = ''A''
		END

	

	IF @LOGCTIPALT = ''A'' AND (  UPDATE (ATSCUSUCAD) OR UPDATE (ATSDDATCAD) OR UPDATE (ATSCUSUALT) OR UPDATE (ATSDDATALT) )
		BEGIN
			RAISERROR (''NÃO É PERMITIDO EDITAR CAMPOS CHAVES!'', 16, 10)
			ROLLBACK
			RETURN
		END
	ELSE 
		IF @LOGCTIPALT = ''I''
			BEGIN
				UPDATE FSAIRTAG_USU
					SET ATSCUSUCAD = SYSTEM_USER, ATSDDATCAD = GETDATE()
					FROM FSAIRTAG_USU ATS, INSERTED
					WHERE ATS.ATSNID_ATS = INSERTED.ATSNID_ATS

					DECLARE TMPCURSINS CURSOR FOR SELECT ATSNID_ATS FROM INSERTED
			OPEN TMPCURSINS
			FETCH NEXT FROM TMPCURSINS INTO @ATSNID_ATS
			WHILE (@@FETCH_STATUS = 0)
				BEGIN
					SET @LOGCID_REC= REPLACE(STR(@ATSNID_ATS,10,0),'' '',''0'')
					SET @LOGMXMLREC= (SELECT * FROM INSERTED WHERE ATSNID_ATS = @ATSNID_ATS FOR XML RAW)

					INSERT INTO FS_CAD..FSLOGLOG ( LOGCTABELA,  LOGCID_REC,  LOGCTIPALT,  LOGMXMLREC, LOGCUSUALT  , LOGDDATALT)  
						                  VALUES (@LOGCTABELA, @LOGCID_REC, @LOGCTIPALT, @LOGMXMLREC, SYSTEM_USER , GETDATE())

					FETCH NEXT FROM TMPCURSINS INTO @ATSNID_ATS
				END
			CLOSE TMPCURSINS
			DEALLOCATE TMPCURSINS
				
			END
		ELSE 
			IF @LOGCTIPALT = ''A'' OR @LOGCTIPALT = ''E'' OR @LOGCTIPALT = ''R''
				BEGIN
					

					UPDATE FSAIRTAG_USU
						SET ATSCUSUALT = SYSTEM_USER, ATSDDATALT = GETDATE()
						FROM FSAIRTAG_USU ATS, INSERTED
						WHERE ATS.ATSNID_ATS = INSERTED.ATSNID_ATS

						DECLARE TMPCURSINS CURSOR FOR SELECT ATSNID_ATS FROM DELETED
			OPEN TMPCURSINS
			FETCH NEXT FROM TMPCURSINS INTO @ATSNID_ATS
			WHILE (@@FETCH_STATUS = 0)
				BEGIN
					SET @LOGCID_REC= REPLACE(STR(@ATSNID_ATS,10,0),'' '',''0'')
					SET @LOGMXMLREC= (SELECT * FROM DELETED WHERE ATSNID_ATS = @ATSNID_ATS FOR XML RAW)

					INSERT INTO FS_CAD..FSLOGLOG ( LOGCTABELA,  LOGCID_REC,  LOGCTIPALT,  LOGMXMLREC, LOGCUSUALT  , LOGDDATALT)  
						                  VALUES (@LOGCTABELA, @LOGCID_REC, @LOGCTIPALT, @LOGMXMLREC, SYSTEM_USER , GETDATE())

					FETCH NEXT FROM TMPCURSINS INTO @ATSNID_ATS
				END
			CLOSE TMPCURSINS
			DEALLOCATE TMPCURSINS
				END
				')