IF OBJECT_ID('FSENTUSU_TR_INC_ALT_DEL','TR') IS NULL
EXEC('
	CREATE TRIGGER FSENTUSU_TR_INC_ALT_DEL
	   ON FSENTUSU
	   AFTER INSERT,UPDATE,DELETE
	AS

	DECLARE @LOGCTABELA VARCHAR(50)
	DECLARE @LOGCID_REC VARCHAR(50)
	DECLARE @LOGMXMLREC XML
	DECLARE @LOGCTIPALT CHAR(01)
	DECLARE @USUNID_ENT INT

	SET @LOGCTABELA = ''FSENTUSU''
	SET @LOGCTIPALT = ''I''

	DECLARE @COUNT AS INT
	SELECT  @COUNT = COUNT(*) FROM DELETED

	IF @COUNT > 0
		BEGIN
			SET @LOGCTIPALT = ''E''
			SELECT @COUNT = COUNT(*) FROM INSERTED
			IF @COUNT > 0
				SET @LOGCTIPALT = ''A''
		END

	

	IF @LOGCTIPALT = ''A'' AND (  UPDATE (USUCUSUCAD) OR UPDATE (USUDDATCAD) OR UPDATE (USUCUSUALT) OR UPDATE (USUDDATALT) )
		BEGIN
			RAISERROR (''NÃO É PERMITIDO EDITAR CAMPOS CHAVES!'', 16, 10)
			ROLLBACK
			RETURN
		END
	ELSE 
		IF @LOGCTIPALT = ''I''
			BEGIN
				UPDATE FSENTUSU
					SET USUCUSUCAD = SYSTEM_USER, USUDDATCAD = GETDATE()
					FROM FSENTUSU USU, INSERTED
					WHERE USU.USUNID_ENT = INSERTED.USUNID_ENT

					DECLARE TMPCURSINS CURSOR FOR SELECT USUNID_ENT FROM INSERTED
			OPEN TMPCURSINS
			FETCH NEXT FROM TMPCURSINS INTO @USUNID_ENT
			WHILE (@@FETCH_STATUS = 0)
				BEGIN
					SET @LOGCID_REC= REPLACE(STR(@USUNID_ENT,10,0),'' '',''0'')
					SET @LOGMXMLREC= (SELECT * FROM INSERTED WHERE USUNID_ENT = @USUNID_ENT FOR XML RAW)

					INSERT INTO FS_CAD..FSLOGLOG ( LOGCTABELA,  LOGCID_REC,  LOGCTIPALT,  LOGMXMLREC, LOGCUSUALT  , LOGDDATALT)  
						                  VALUES (@LOGCTABELA, @LOGCID_REC, @LOGCTIPALT, @LOGMXMLREC, SYSTEM_USER , GETDATE() )

					FETCH NEXT FROM TMPCURSINS INTO @USUNID_ENT
				END
			CLOSE TMPCURSINS
			DEALLOCATE TMPCURSINS
				
			END
		ELSE 
			IF @LOGCTIPALT = ''A'' OR @LOGCTIPALT = ''E'' OR @LOGCTIPALT = ''R''
				BEGIN
					

					UPDATE FSENTUSU
						SET USUCUSUALT = SYSTEM_USER, USUDDATALT = GETDATE()
						FROM FSENTUSU USU, INSERTED
						WHERE USU.USUNID_ENT = INSERTED.USUNID_ENT

						DECLARE TMPCURSINS CURSOR FOR SELECT USUNID_ENT FROM DELETED
			OPEN TMPCURSINS
			FETCH NEXT FROM TMPCURSINS INTO @USUNID_ENT
			WHILE (@@FETCH_STATUS = 0)
				BEGIN
					SET @LOGCID_REC= REPLACE(STR(@USUNID_ENT,10,0),'' '',''0'')
					SET @LOGMXMLREC= (SELECT * FROM DELETED WHERE USUNID_ENT = @USUNID_ENT FOR XML RAW)

					INSERT INTO FS_CAD..FSLOGLOG ( LOGCTABELA,  LOGCID_REC,  LOGCTIPALT,  LOGMXMLREC, LOGCUSUALT  , LOGDDATALT)  
						                  VALUES (@LOGCTABELA, @LOGCID_REC, @LOGCTIPALT, @LOGMXMLREC, SYSTEM_USER , GETDATE())

					FETCH NEXT FROM TMPCURSINS INTO @USUNID_ENT
				END
			CLOSE TMPCURSINS
			DEALLOCATE TMPCURSINS
				END
				')